/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-07-21 01:45:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userEnrollForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/userEnrollFormStyle.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <div class=\"outer\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <span class=\"subTitle\">\r\n");
      out.write("            <b class=\"font-purple\">신규회원 </b><b>가입</b>\r\n");
      out.write("        </span>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div class=\"joimForm\">\r\n");
      out.write("            <form action=\"join.me\" method=\"post\" id=\"joinUser\">\r\n");
      out.write("                <table class=\"joinTable\" align=\"center\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th width=\"20%\">*아이디</th>\r\n");
      out.write("                        <td width=\"60%\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"userId\" id=\"userId\" required>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <button type=\"button\" class=\"button-clear\" id=\"btnId\" onclick=\"idCheck();\">중복확인</button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                    	<th></th>\r\n");
      out.write("                        <td colspan=\"2\" class=\"font-info\">\r\n");
      out.write("                            <div id=\"idcheck\">\r\n");
      out.write("		                        영소문자, 숫자, _입력가능, 최소 4글자 최대 15글자 입력해주세요.\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>*비밀번호</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"password\" class=\"form-control\" name=\"userPwd\" id=\"userPwd\" required>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>*비밀번호 확인</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"password\" class=\"form-control\" name=\"userPwdChk\" id=\"userPwdChk\" required>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                    	<th></th>\r\n");
      out.write("                        <td colspan=\"2\" class=\"font-info\">\r\n");
      out.write("                        	<div id=\"pwdCheck\">\r\n");
      out.write("                        		최소 4글자 이상 동일하게 입력해주세요.\r\n");
      out.write("                        	</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>*이름</th>\r\n");
      out.write("                        <td><input type=\"text\" class=\"form-control\" name=\"userName\" id=\"userName\" required></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>*닉네임</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"userNickname\" id=\"userNickname\" required>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <button type=\"button\" class=\"button-clear\" id=\"btnNickname\" onclick=\"nicknameCheck();\">중복확인</button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                    	<th></th>\r\n");
      out.write("                        <td colspan=\"2\" class=\"font-info\">\r\n");
      out.write("                            <div id=\"nicknamecheck\">\r\n");
      out.write("		                        영문자, 한글, 숫자 입력가능, 최소 2글자 최대 12글자 입력해주세요.\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>*이메일</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"email\" class=\"form-control\" name=\"userEmail\" id=\"userEmail\" required>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <button type=\"button\" class=\"button-clear\">인증코드 발송</button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>*인증코드</th>\r\n");
      out.write("                        <td><input type=\"text\" class=\"form-control\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <!-- 하이픈형식 000-0000-0000 -->\r\n");
      out.write("                        <th>*휴대폰 번호</th>\r\n");
      out.write("                    <td><input type=\"text\" class=\"form-control\" name=\"userPhone\" id=\"userPhone\" required></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <!--\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>프로필사진</th>\r\n");
      out.write("                            <td>\r\n");
      out.write("                            <label class=\"button-clear\" for=\"profile\">파일선택</label>\r\n");
      out.write("                            &ensp;\r\n");
      out.write("                            <input type=\"file\" id=\"profile\" style=\"border: none;\">\r\n");
      out.write("                            <p>이미지는 60px X 60px 사이즈에 최적화</p>\r\n");
      out.write("                            <p>gif, jpg, png파일만 가능하며 용량 5MB 이하만 등록됩니다.</p>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    --> \r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>*관심장르</th>\r\n");
      out.write("                        <td colspan=\"2\">\r\n");
      out.write("                            <div class=\"genreList\">\r\n");
      out.write("                                <div class=\"genreChk\">\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"genre1\" name=\"userGenre\" class=\"userGenre\" value=\"액션\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"genreName\">\r\n");
      out.write("                                    <label for=\"genre1\">액션</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"genreChk\">\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"genre2\" name=\"userGenre\" class=\"userGenre\" value=\"멜로\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"genreName\">\r\n");
      out.write("                                    <label for=\"genre2\">멜로</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"genreChk\">\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"genre3\" name=\"userGenre\" class=\"userGenre\" value=\"공포\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"genreName\">\r\n");
      out.write("                                    <label for=\"genre3\">공포</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"genreChk\">\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"genre4\" name=\"userGenre\" class=\"userGenre\" value=\"코미디\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"genreName\">\r\n");
      out.write("                                    <label for=\"genre4\">코미디</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"genreChk\">\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"genre5\" name=\"userGenre\" class=\"userGenre\" value=\"애니메이션\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"genreName\">\r\n");
      out.write("                                    <label for=\"genre5\">애니메이션</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <button type=\"button\" class=\"btn button-gray\">취소</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn button-purple\" id=\"btnJoin\">회원가입</button>\r\n");
      out.write("         </form>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <script>\r\n");
      out.write("         \r\n");
      out.write("         //아이디 중복 및 유효성 검사\r\n");
      out.write("         function idCheck() {\r\n");
      out.write("        	 \r\n");
      out.write("        	 var $idchk = $(\"#joinUser input[name=userId]\");\r\n");
      out.write("        	 var regExp = /^[a-z0-9_]{4,15}$/;\r\n");
      out.write("        	 \r\n");
      out.write("//            	 console.log($idchk.val());\r\n");
      out.write("             if(!regExp.test($idchk.val())){\r\n");
      out.write("				 $(\"#idcheck\").css(\"color\",\"red\").text(\"유효하지 않는 아이디입니다. 영소문자, 숫자, _입력가능, 최소 4글자 최대 15글자 입력해주세요.\");\r\n");
      out.write("				 $(\"#idcheck\").focus();\r\n");
      out.write("                 $(\"#userId\").removeClass('chked');\r\n");
      out.write("                 return false;\r\n");
      out.write("             }else{\r\n");
      out.write("        		 $.ajax({\r\n");
      out.write("        			 url : \"idCheck.me\",\r\n");
      out.write("					 data : {\r\n");
      out.write("						 checkId : $idchk.val()\r\n");
      out.write("						 },\r\n");
      out.write("					 success : function(result){\r\n");
      out.write("			 			 console.log(result);\r\n");
      out.write("						 if(result=='NNNNY'){\r\n");
      out.write("							 $(\"#idcheck\").css(\"color\",\"yellowgreen\").text(\"사용가능한 아이디입니다.\");\r\n");
      out.write("			                 $(\"#userId\").addClass('chked');\r\n");
      out.write("						 }else{\r\n");
      out.write("							 $(\"#idcheck\").css(\"color\",\"red\").text(\"사용중이거나 탈퇴한 아이디입니다.\");\r\n");
      out.write("			                 $(\"#userId\").removeClass('chked');\r\n");
      out.write("						 }\r\n");
      out.write("					 },\r\n");
      out.write("					 error : function(){\r\n");
      out.write("						 console.log(\"ajax 통신 실패\");\r\n");
      out.write("						 }\r\n");
      out.write("				 })\r\n");
      out.write("             }\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         //닉네임 중복 및 유효성 검사\r\n");
      out.write("         function nicknameCheck() {\r\n");
      out.write("        	 \r\n");
      out.write("        	 var $nicknamechk = $(\"#joinUser input[name=userNickname]\");\r\n");
      out.write("        	 var regExp = /^[가-힣a-zA-Z0-9]{2,6}$/;\r\n");
      out.write("        	 \r\n");
      out.write("           	 console.log($nicknamechk.val());\r\n");
      out.write("             if(!regExp.test($nicknamechk.val())){\r\n");
      out.write("				 $(\"#nicknamecheck\").css(\"color\",\"red\").text(\"유효하지 않는 닉네임입니다. 영문자, 한글, 숫자 입력가능, 최소 2글자 최대 6글자 입력해주세요\");\r\n");
      out.write("				 $(\"#nicknamecheck\").focus();\r\n");
      out.write("                 $(\"#userNickname\").removeClass('chked');\r\n");
      out.write("                 return false;\r\n");
      out.write("             }else{\r\n");
      out.write("        		 $.ajax({\r\n");
      out.write("        			 url : \"nicknameCheck.me\",\r\n");
      out.write("					 data : {\r\n");
      out.write("						 checkNickname : $nicknamechk.val()\r\n");
      out.write("						 },\r\n");
      out.write("					 success : function(result){\r\n");
      out.write("			 			 console.log(result);\r\n");
      out.write("						 if(result=='NNNNY'){\r\n");
      out.write("							 $(\"#nicknamecheck\").css(\"color\",\"yellowgreen\").text(\"사용가능한 닉네임입니다.\");\r\n");
      out.write("			                 $(\"#userNickname\").addClass('chked');\r\n");
      out.write("						 }else{\r\n");
      out.write("							 $(\"#nicknamecheck\").css(\"color\",\"red\").text(\"사용할수 없는 닉네임입니다.\");\r\n");
      out.write("			                 $(\"#userNickname\").removeClass('chked');\r\n");
      out.write("						 }\r\n");
      out.write("					 },\r\n");
      out.write("					 error : function(){\r\n");
      out.write("						 console.log(\"ajax 통신 실패\");\r\n");
      out.write("						 }\r\n");
      out.write("				 })\r\n");
      out.write("             }\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         //비밀번호 일치 및 유효성 검사\r\n");
      out.write("	        $(function(){\r\n");
      out.write("	        	var $userPwd = $(\"#joinUser input[name=userPwd]\");\r\n");
      out.write("	        	var $userPwdChk = $(\"#joinUser input[name=userPwdChk]\");\r\n");
      out.write("	        	\r\n");
      out.write("		        	$userPwd.keyup(function(){\r\n");
      out.write("			        	if($userPwd.val().length>=4){\r\n");
      out.write("		        			$.ajax({\r\n");
      out.write("							url : \"pwdCheck.me\",\r\n");
      out.write("							data : {\r\n");
      out.write("								userPwd : $userPwd.val(),\r\n");
      out.write("								userPwdChk : $userPwdChk.val()\r\n");
      out.write("							},\r\n");
      out.write("							success : function(result){\r\n");
      out.write("								console.log(result);\r\n");
      out.write("								if(result=='NNNNY'){\r\n");
      out.write("									$(\"#pwdCheck\").show();\r\n");
      out.write("									$(\"#pwdCheck\").css(\"color\",\"yellowgreen\").text(\"비밀번호가 일치합니다.\");\r\n");
      out.write("					                $(\"#userPwd\").addClass('chked');\r\n");
      out.write("								}else{\r\n");
      out.write("									$(\"#pwdCheck\").show();\r\n");
      out.write("									$(\"#pwdCheck\").css(\"color\",\"red\").text(\"비밀번호가 일치하지 않습니다\");\r\n");
      out.write("					                $(\"#userPwd\").removeClass('chked');\r\n");
      out.write("								}\r\n");
      out.write("							},\r\n");
      out.write("							error : function(){\r\n");
      out.write("								console.log(\"ajax 통신 실패\");\r\n");
      out.write("							}\r\n");
      out.write("						})\r\n");
      out.write("			        	}else{\r\n");
      out.write("							$(\"#pwdCheck\").css(\"color\",\"red\").text(\"비밀번호를 4자리 이상 입력해주세요.\");\r\n");
      out.write("			                $(\"#userPwd\").removeClass('chked');\r\n");
      out.write("			        	}\r\n");
      out.write("		        	})\r\n");
      out.write("		        	\r\n");
      out.write("		        	$userPwdChk.keyup(function(){\r\n");
      out.write("			        	if($userPwdChk.val().length>=4){\r\n");
      out.write("		        			$.ajax({\r\n");
      out.write("							url : \"pwdCheck.me\",\r\n");
      out.write("							data : {\r\n");
      out.write("								userPwd : $userPwd.val(),\r\n");
      out.write("								userPwdChk : $userPwdChk.val()\r\n");
      out.write("							},\r\n");
      out.write("							success : function(result){\r\n");
      out.write("								console.log(result);\r\n");
      out.write("								if(result=='NNNNY'){\r\n");
      out.write("									$(\"#pwdCheck\").show();\r\n");
      out.write("									$(\"#pwdCheck\").css(\"color\",\"yellowgreen\").text(\"비밀번호가 일치합니다.\");\r\n");
      out.write("					                $(\"#userPwd\").addClass('chked');\r\n");
      out.write("								}else{\r\n");
      out.write("									$(\"#pwdCheck\").show();\r\n");
      out.write("									$(\"#pwdCheck\").css(\"color\",\"red\").text(\"비밀번호가 일치하지 않습니다\");\r\n");
      out.write("					                $(\"#userPwd\").removeClass('chked');\r\n");
      out.write("								}\r\n");
      out.write("							},\r\n");
      out.write("							error : function(){\r\n");
      out.write("								console.log(\"ajax 통신 실패\");\r\n");
      out.write("							}\r\n");
      out.write("						})\r\n");
      out.write("			        	}else{\r\n");
      out.write("							$(\"#pwdCheck\").css(\"color\",\"red\").text(\"비밀번호를 4자리 이상 입력해주세요.\");\r\n");
      out.write("			                $(\"#userPwd\").removeClass('chked');\r\n");
      out.write("			        	}\r\n");
      out.write("		        	})\r\n");
      out.write("	        	})\r\n");
      out.write("         \r\n");
      out.write("        //회원가입버튼 클릭시 유효성검사(아이디, 비밀번호, 닉네임)\r\n");
      out.write("   		$(document).ready(function(){\r\n");
      out.write("   			//이메일용이니까 나중에 옮길거!!!!!!!!!!\r\n");
      out.write("   			var regExp = /^([0-9a-zA-Z_-]+)@([0-9a-zA-Z_-]+)(\\.[0-9a-zA-Z_-]+){1,2}$/;\r\n");
      out.write("   			$(\"#btnJoin\").click(function(){\r\n");
      out.write("				//필수입력\r\n");
      out.write("   				if($(\"#userId\").val()==\"\"){\r\n");
      out.write("   					alert(\"아이디 입력은 필수입니다.\");\r\n");
      out.write("   					$(\"#userId\").focus();\r\n");
      out.write("   				}else if($(\"#userPwd\").val()==\"\"){\r\n");
      out.write("   					alert(\"비밀번호 입력은 필수입니다.\");\r\n");
      out.write("   					$(\"#userPwd\").focus();\r\n");
      out.write("   				}else if($(\"#userPwdChk\").val()==\"\"){\r\n");
      out.write("   					alert(\"비밀번호확인 입력은 필수입니다.\");\r\n");
      out.write("   					$(\"#userPwdChk\").focus();\r\n");
      out.write("   				}else if($(\"#userName\").val()==\"\"){\r\n");
      out.write("   					alert(\"이름 입력은 필수입니다.\");\r\n");
      out.write("   					$(\"#userName\").focus();\r\n");
      out.write("   				}else if($(\"#userNickname\").val()==\"\"){\r\n");
      out.write("   					alert(\"닉네임 입력은 필수입니다.\");\r\n");
      out.write("   					$(\"#userNickname\").focus();\r\n");
      out.write("   				}else if($(\"#userEmail\").val()==\"\"){\r\n");
      out.write("   					alert(\"이메일 입력은 필수입니다.\");\r\n");
      out.write("   					$(\"#userEmail\").focus();\r\n");
      out.write("   				}else if($(\"#userPhone\").val()==\"\"){\r\n");
      out.write("   					alert(\"휴대폰번호 입력은 필수입니다.\");\r\n");
      out.write("   					$(\"#userPhone\").focus();\r\n");
      out.write("   				}else if($(\"input:checkbox[name='userGenre']\").is(\":checked\")==false){\r\n");
      out.write("   					alert(\"관심있는 장르 적어도 하나를 선택해주세요.\");\r\n");
      out.write("   					$(\"#genre1\").focus();\r\n");
      out.write("   				//중복체크\r\n");
      out.write("   				}else if($(\"#userId\").hasClass(\"chked\")==false){\r\n");
      out.write("   					alert(\"아이디 중복체크 해주세요.\");\r\n");
      out.write("   					$(\"#userId\").focus();\r\n");
      out.write("   				}else if($(\"#userNickname\").hasClass(\"chked\")==false){\r\n");
      out.write("   					alert(\"닉네임 중복체크 해주세요.\");\r\n");
      out.write("   					$(\"#userNickname\").focus();\r\n");
      out.write("   				//비밀번호일치\r\n");
      out.write("   				}else if($(\"#userPwd\").hasClass(\"chked\")==false){\r\n");
      out.write("   					alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("   					$(\"#userPwd\").focus();\r\n");
      out.write("				//이메일 형식 유효성 ==> 메일인증 기능추가시 버튼으로 옮기기!!!!!!!!!!\r\n");
      out.write("   				}else if(!regExp.test($(\"#userEmail\").val())){\r\n");
      out.write("   					alert(\"이메일 형식을 확인해주세요\");\r\n");
      out.write("   					$(\"#userEmail\").focus();\r\n");
      out.write("   				}else{\r\n");
      out.write("   					$(\"#joinUser\").submit();\r\n");
      out.write("   				}\r\n");
      out.write("   			});\r\n");
      out.write("   		});\r\n");
      out.write("         \r\n");
      out.write("			</script>\r\n");
      out.write("         \r\n");
      out.write("         </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
