/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-07-20 08:31:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.poster;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class RankingPs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1658302804963L));
    _jspx_dependants.put("jar:file:/C:/Final_Pr_gitfolder/FinalProject/FinalProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/ottRecomend.css\">\r\n");
      out.write("<style>\r\n");
      out.write("	.nav-link:hover{\r\n");
      out.write("		cursor:pointer;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("		 <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\"/>\r\n");
      out.write("		 <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("		 <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("		 <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("		 <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<footer>\r\n");
      out.write("	<!-- Products Start -->\r\n");
      out.write("	<div class=\"container-fluid about py-1\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"section-title position-relative text-center mx-auto mb-5 pb-3\" style=\"max-width: 600px;\">\r\n");
      out.write("						<h1 class=\"text-primary font-secondary\" style=\"color: burlywood !important;\">Ott & Rank</h1>\r\n");
      out.write("						<h6 class=\"display-42 text-uppercase\">Enjoy your life with us!</h6>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"tab-class text-center\">\r\n");
      out.write("						<ul class=\"nav nav-tabs d-inline-flex justify-content-center bg-dark text-uppercase border-inner p-4 mb-5\" role=\"tablist\">\r\n");
      out.write("								<li class=\"nav-item\">\r\n");
      out.write("\r\n");
      out.write("										<a id=\"pills-kino-tab\" class=\"nav-link active\" data-tab=\"tab1\"  style=\"color: bisque !important;\">kino</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"nav-item\" >\r\n");
      out.write("										<a id=\"pills-netflix-tab\" class=\"nav-link\" data-tab=\"tab2\"  style=\"color: bisque !important;\">netflix</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"nav-item\" >\r\n");
      out.write("										<a id=\"pills-wavve-tab\" class=\"nav-link\" data-tab=\"tab3\"  style=\"color: bisque !important;\">wavve</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"nav-item\" >\r\n");
      out.write("									<a id=\"pills-tving-tab\" class=\"nav-link\" data-tab=\"tab4\"  style=\"color: bisque !important;\">tving</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li class=\"nav-item\" >\r\n");
      out.write("								<a id=\"pills-disney-tab\" class=\"nav-link\" data-tab=\"tab5\"  style=\"color: bisque !important;\">disney</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item\" >\r\n");
      out.write("							<a id=\"pills-watcha-tab\" class=\"nav-link\" data-tab=\"tab6\"  style=\"color: bisque !important;\">watcha</a>\r\n");
      out.write("					</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<div class=\"tab-content\">\r\n");
      out.write("								<div id=\"kino\">\r\n");
      out.write("									<div class=\"row g-3\" style=\"align-items: center;flex-direction: column;\">\r\n");
      out.write("												");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("												\r\n");
      out.write("											</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								\r\n");
      out.write("						</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<script>\r\n");
      out.write("					\r\n");
      out.write("	\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("					$(\".nav-link\").click(function(){\r\n");
      out.write("							\r\n");
      out.write("							var num = $(this).text();\r\n");
      out.write("							\r\n");
      out.write("							$('li.nav-item a').removeClass('active');\r\n");
      out.write("							$(this).addClass('active');\r\n");
      out.write("							\r\n");
      out.write("							$(\".tab-content\").children().attr('id',num);\r\n");
      out.write("							\r\n");
      out.write("							console.log(num);\r\n");
      out.write("							\r\n");
      out.write("							$.ajax({\r\n");
      out.write("								url: \"ajax.do\",\r\n");
      out.write("								data : {name :  num},\r\n");
      out.write("								success : function(result){\r\n");
      out.write("									console.log(result);\r\n");
      out.write("									var str = \"\";\r\n");
      out.write("									\r\n");
      out.write("									$.each (result, function(i){\r\n");
      out.write("										\r\n");
      out.write("										str += \"<div class='row g-3' style='align-items: center;flex-direction: column;'>\" \r\n");
      out.write("											+\"<div class='col-lg-6' style='max-width:100%; width: 1000px;'>\"\r\n");
      out.write("											+\"<div class='d-flex h-100' style='width: 100%;  height: 100px !important;max-height: 100% !important;'>\"\r\n");
      out.write("											+\"<div class='flex-shrink-0'>\"\r\n");
      out.write("											+\"<img class='img-fluid' src='\"+result[i].PostImg+\"' style='width: 100px; height: 100px;'>\"\r\n");
      out.write("											+\"</div>\"\r\n");
      out.write("											+\"<div class='d-flex flex-column justify-content-center text-start bg-secondary border-inner px-4' style='width: 100%;'>\"\r\n");
      out.write("											+\"<h5 class='text-uppercase'><b>\"+(i+1)+\"</b></h5>\"\r\n");
      out.write("											+\"<span><b>\"+result[i].postName+\"</b></span>\"\r\n");
      out.write("											+\"</div>\"\r\n");
      out.write("										+\"</div>\"\r\n");
      out.write("											+\"</div>\"\r\n");
      out.write("											+\"</div>\"\r\n");
      out.write("									});\r\n");
      out.write("									\r\n");
      out.write("									$(\"#\"+num).html(str);\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								},\r\n");
      out.write("								error : function(){\r\n");
      out.write("									console.log(\"ajax 통신 실패\");\r\n");
      out.write("								}\r\n");
      out.write("							})\r\n");
      out.write("							\r\n");
      out.write("					})\r\n");
      out.write("					\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("			\r\n");
      out.write("				\r\n");
      out.write("				</script>\r\n");
      out.write("		</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Products End -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/poster/RankingPs.jsp(58,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("m");
      // /WEB-INF/views/poster/RankingPs.jsp(58,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/poster/RankingPs.jsp(58,12) '${pr }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pr }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/poster/RankingPs.jsp(58,12) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("													<div class=\"col-lg-6\" style=\"max-width:100%; width: 1000px;\">\r\n");
            out.write("															<div class=\"d-flex h-100\" style=\"width: 100%;  height: 100px !important;max-height: 100% !important;\">\r\n");
            out.write("																	<div class=\"flex-shrink-0\">\r\n");
            out.write("																			<img class=\"img-fluid\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.postImg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\" style=\"width: 100px; height: 100px;\">\r\n");
            out.write("																			\r\n");
            out.write("																	</div>\r\n");
            out.write("																	<div class=\"d-flex flex-column justify-content-center text-start bg-secondary border-inner px-4\" style=\"width: 100%;\">\r\n");
            out.write("																			<h5 class=\"text-uppercase\"><b>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</b></h5>\r\n");
            out.write("																			<span><b>\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.postName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"</b></span>\r\n");
            out.write("																	</div>\r\n");
            out.write("															</div>\r\n");
            out.write("													</div>\r\n");
            out.write("													");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
