/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-07-30 17:39:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.poster;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class RecomPs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<title>Future Imperfect by HTML5 UP</title>\r\n");
      out.write("		<meta charset=\"utf-8\"/>\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\"/>\r\n");
      out.write("		\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"./resources/css/recom_style.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"./resources/css/recom2_styles.css\"/>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"./resources/js/recom_scripts.js\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("		 <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("		 <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("		 <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("		<style>\r\n");
      out.write("			/* Make the image fully responsive */\r\n");
      out.write("			.carousel-inner img {\r\n");
      out.write("				height: 500px;\r\n");
      out.write("				width: 500px;\r\n");
      out.write("			}\r\n");
      out.write("			</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("	<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginUser}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../chat/chat.jsp", out, false);
      out.write("\r\n");
      out.write("    </c:if>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"./resources/js/recom_main.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<footer>\r\n");
      out.write("		<!-- Portfolio-->\r\n");
      out.write("		<section class=\"content-section\" id=\"portfolio\">\r\n");
      out.write("			<div class=\"container px-3 px-lg-4\">\r\n");
      out.write("					<div class=\"content-section-heading text-center\">\r\n");
      out.write("						<header class=\"bg-dark py-3\">\r\n");
      out.write("							<h1 class=\"mb-3\" style=\"color:bisque; font-weight: bolder; font-size:40px !important;\">Kind Of Poster</h1>\r\n");
      out.write("							<p class=\"lead fw-normal text-white-50 mb-0\" style=\"color:bisque; font-size:20px;\">Enjoy your life with us!</p>\r\n");
      out.write("						</header>\r\n");
      out.write("					</div>\r\n");
      out.write("					<br><br><br>\r\n");
      out.write("					<div class=\"row gx-3\" style=\"flex-direction:row; flex-wrap:wrap;\">\r\n");
      out.write("							<div class=\"col-lg-6\" style=\"height: 200px; width: 250px;\">\r\n");
      out.write("									<a class=\"portfolio-item\" href=\"list.ps?list=액션\"  style=\"height: 200px; width: 250px;\">\r\n");
      out.write("											<img class=\"img-fluid\" src=\"./resources/images/images.jpg\" style=\"height: 200px  width: 100%;\"/>\r\n");
      out.write("									</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-lg-6\" style=\"height: 200px; width: 250px;\">\r\n");
      out.write("									<a class=\"portfolio-item\" href=\"list.ps?list=멜로/로맨스\" style=\"height: 200px; width: 250px;\">\r\n");
      out.write("											<img class=\"img-fluid\" src=\"./resources/images/romance-club-stories-i-play-icon.png\"style=\"height: 200px; width: 100%;\"/>\r\n");
      out.write("									</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-lg-6\" style=\"height: 200px; width: 250px;\">\r\n");
      out.write("									<a class=\"portfolio-item\" href=\"list.ps?list=코미디\" style=\"height: 200px; width: 250px;\">\r\n");
      out.write("											<img class=\"img-fluid\" src=\"./resources/images/Hera-Pheri.jpeg\" style=\"height: 200px; width: 100%;\"/>\r\n");
      out.write("									</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-lg-6\" style=\"height: 200px; width: 250px;\">\r\n");
      out.write("									<a class=\"portfolio-item\" href=\"list.ps?list=애니메이션\" style=\"height: 200px; width: 250px;\">\r\n");
      out.write("											<img class=\"img-fluid\" src=\"./resources/images/1050898-view-conference-2019-celebrating-best-animation-vfx-and-visual-storytelling.jpg\" style=\"height: 200px; width: 100%;\" />\r\n");
      out.write("									</a>\r\n");
      out.write("							</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section class=\"news section illustration-section-01\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"news-inner section-inner\">\r\n");
      out.write("				<div class=\"section-header center-content\">\r\n");
      out.write("					<div class=\"container-xs\">\r\n");
      out.write("						<h2 class=\"mt-0 mb-16\" style=\"font-weight: 700; font-family:Inter, sans-serif;\">\r\n");
      out.write("							Recommend for you!\r\n");
      out.write("						</h2>\r\n");
      out.write("						<br>\r\n");
      out.write("						<p class=\"mb-0\" style=\"font-weight: 500; font-family:Inter, sans-serif;\">\r\n");
      out.write("							We recommend based on your preferences.Find all the movies you want and enjoy the benefits!\r\n");
      out.write("						</p>\r\n");
      out.write("						<br>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"tiles-wrap\">\r\n");
      out.write("					<article class=\"tiles-item reveal-from-bottom\">\r\n");
      out.write("						<div class=\"tiles-item-inner has-shadow\">\r\n");
      out.write("							<figure class=\"news-item-image m-0\">\r\n");
      out.write("								<img\r\n");
      out.write("									src=\"images/news-image-01.jpg\"\r\n");
      out.write("									alt=\"News 01\"\r\n");
      out.write("									width=\"344\"\r\n");
      out.write("									height=\"194\"\r\n");
      out.write("								/>\r\n");
      out.write("							</figure>\r\n");
      out.write("							<div class=\"news-item-content\">\r\n");
      out.write("								<div class=\"news-item-body\">\r\n");
      out.write("									<h3\r\n");
      out.write("										class=\"news-item-title h4 mt-0 mb-8\"\r\n");
      out.write("									>\r\n");
      out.write("										<a href=\"#\"\r\n");
      out.write("											>How to build\r\n");
      out.write("											anything</a\r\n");
      out.write("										>\r\n");
      out.write("									</h3>\r\n");
      out.write("									<p class=\"mb-16 text-sm\">\r\n");
      out.write("										Lorem ipsum dolor sit amet,\r\n");
      out.write("										consectetur adipiscing elit,\r\n");
      out.write("										sed do eiusmod tempor\r\n");
      out.write("										incididunt ut et dolore\r\n");
      out.write("										magna aliqua. Ut enim ad\r\n");
      out.write("										minim veniam, quis nostrud\r\n");
      out.write("										exercitation ullamco laboris\r\n");
      out.write("										nisi ut aliquip ex.\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div\r\n");
      out.write("									class=\"news-item-more text-xs mb-8\"\r\n");
      out.write("								>\r\n");
      out.write("									<a href=\"#\">Read more</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</article>\r\n");
      out.write("					<article\r\n");
      out.write("						class=\"tiles-item reveal-from-bottom\"\r\n");
      out.write("						data-reveal-delay=\"200\"\r\n");
      out.write("					>\r\n");
      out.write("						<div class=\"tiles-item-inner has-shadow\">\r\n");
      out.write("							<figure class=\"news-item-image m-0\">\r\n");
      out.write("								<img\r\n");
      out.write("									src=\"https://nujhrcqkiwag1408085.cdn.ntruss.com/static/upload/movie_poster_images/280x400/movie_76722_1651460799.jpeg\"\r\n");
      out.write("									alt=\"News 02\"\r\n");
      out.write("									width=\"344\"\r\n");
      out.write("									height=\"194\"\r\n");
      out.write("								/>\r\n");
      out.write("							</figure>\r\n");
      out.write("							<div class=\"news-item-content\">\r\n");
      out.write("								<div class=\"news-item-body\">\r\n");
      out.write("									<h3\r\n");
      out.write("										class=\"news-item-title h4 mt-0 mb-8\"\r\n");
      out.write("									>\r\n");
      out.write("										<a href=\"#\"\r\n");
      out.write("											>How to build\r\n");
      out.write("											anything</a\r\n");
      out.write("										>\r\n");
      out.write("									</h3>\r\n");
      out.write("									<p class=\"mb-16 text-sm\">\r\n");
      out.write("										Lorem ipsum dolor sit amet,\r\n");
      out.write("										consectetur adipiscing elit,\r\n");
      out.write("										sed do eiusmod tempor\r\n");
      out.write("										incididunt ut et dolore\r\n");
      out.write("										magna aliqua. Ut enim ad\r\n");
      out.write("										minim veniam, quis nostrud\r\n");
      out.write("										exercitation ullamco laboris\r\n");
      out.write("										nisi ut aliquip ex.\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div\r\n");
      out.write("									class=\"news-item-more text-xs mb-8\"\r\n");
      out.write("								>\r\n");
      out.write("									<a href=\"#\">Read more</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</article>\r\n");
      out.write("					<article\r\n");
      out.write("						class=\"tiles-item reveal-from-bottom\"\r\n");
      out.write("						data-reveal-delay=\"400\"\r\n");
      out.write("					>\r\n");
      out.write("						<div class=\"tiles-item-inner has-shadow\">\r\n");
      out.write("							<figure class=\"news-item-image m-0\">\r\n");
      out.write("								<img\r\n");
      out.write("									src=\"images/news-image-03.jpg\"\r\n");
      out.write("									alt=\"News 03\"\r\n");
      out.write("									width=\"344\"\r\n");
      out.write("									height=\"194\"\r\n");
      out.write("								/>\r\n");
      out.write("							</figure>\r\n");
      out.write("							<div class=\"news-item-content\">\r\n");
      out.write("								<div class=\"news-item-body\">\r\n");
      out.write("									<h3\r\n");
      out.write("										class=\"news-item-title h4 mt-0 mb-8\"\r\n");
      out.write("									>\r\n");
      out.write("										<a href=\"#\"\r\n");
      out.write("											>How to build\r\n");
      out.write("											anything</a\r\n");
      out.write("										>\r\n");
      out.write("									</h3>\r\n");
      out.write("									<p class=\"mb-16 text-sm\">\r\n");
      out.write("										Lorem ipsum dolor sit amet,\r\n");
      out.write("										consectetur adipiscing elit,\r\n");
      out.write("										sed do eiusmod tempor\r\n");
      out.write("										incididunt ut et dolore\r\n");
      out.write("										magna aliqua. Ut enim ad\r\n");
      out.write("										minim veniam, quis nostrud\r\n");
      out.write("										exercitation ullamco laboris\r\n");
      out.write("										nisi ut aliquip ex.\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div\r\n");
      out.write("									class=\"news-item-more text-xs mb-8\"\r\n");
      out.write("								>\r\n");
      out.write("									<a href=\"#\">Read more</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</article>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
